### ISSUE TITLE
Improve PIT Run Button Design

### ISSUE THREAD

**Issue by emuguy1** [amosproj/amos2023ws02-pitest-ide-plugin#119]
## User story

1. As a user of our plugin
2. I want / need a unique design for our Pitest run button
3. So that I can clearly recognize it

## Acceptance criteria

- the run button is clearly visible in the sidebar of the IDE
- it has a recognizable and clear design (For example two run buttons overlayerd, one in the PITest pink and one gray - Make it so everyone clearly sees that it is not a button to reduce the size of the class or anything but that it has something to do with our plugin
- the run button is correctly positioned next to the class names

## Definition of done (DoD)

- All acceptance criteria are met.
- Work products are uploaded to the Github repository.
- A pull request is created for each related branch.
- The work products in the pull requests are reviewed.
- Github CI Workflow passes for the branches
- The corresponding branches are merged and closed.
- The bill of materials section of the planning documents is updated.
- Tests are written for the added features, if suitable

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by nikomall34** [comment]
![Image](https://github.com/amosproj/amos2023ws02-pitest-ide-plugin/assets/62472091/a22fa3f2-4065-465f-9315-06a0fcb2701b)
