### ISSUE TITLE
Linemarkers emit Warnings

### ISSUE THREAD

**Issue by lheimbs** [amosproj/amos2023ws02-pitest-ide-plugin#129]
**Describe the bug**
Everytime our LineMarkers get created they emit this warning:

> 2023-12-12 10:54:19,206 [   6637]   WARN - #c.i.c.d.LineMarkerInfo - Performance warning: LineMarker is supposed to be registered for leaf elements only, but got: PsiClass:Palindrome (class com.intellij.psi.impl.source.PsiClassImpl) instead. First child: PsiModifierList:public (class com.intellij.psi.impl.source.PsiModifierListImpl)
Please see LineMarkerProvider#getLineMarkerInfo(PsiElement) javadoc for detailed explanations.

**To Reproduce**

1. Run the plugin on any class
2. Inspec the console/log output

**Expected behavior**
No warnings get emitted

**Comment by nikomall34** [comment]
This was fixed with the issue that the Gutter appears next to annotations. So with our current state this warning shouldn't appear anymore.

**Comment by emuguy1** [comment]
Close as completed
