### ISSUE TITLE
Bundle MutationListener Plugin with our Override using the Jetbrains Plugin

### ISSUE THREAD

**Issue by Felix-012** [amosproj/amos2023ws02-pitest-ide-plugin#172]
## User story

1. As a user
2. I want / need to our mutation listener plugin to be bundled with our override plugin using the jetbrains plugin
3. So that I don't have further complexities using the pitest plugin

## Acceptance criteria

- Mutation Listener Plugin is bundled with our override plugin using the jetbrains plugin
- Edit the existing error message for missing plugins appropriately

## Definition of done (DoD)

- All acceptance criteria are met.
- Work products are uploaded to the GitHub repository.
- A pull request is created for each related branch.
- The work products in the pull requests are reviewed.
- GitHub CI Workflow passes for the branches
- The corresponding branches are merged and closed.
- The bill of materials section of the planning documents is updated.
- Tests are written for the added features, if suitable

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by emuguy1** [comment]
@lheimbs @nikomall34 
Would you say this ticket is understandable in that we want to bundle the mutation listener stuff as discussed in the industry partner meeting?

**Comment by lheimbs** [comment]
Its not the jetbrains plugin but the gradle plugin we - if at all - should do the bundling with I think.
But @nikomall34 and I discussed this on Friday and we felt it would be best to publish the coverage reporter properly and then have the gradle plugin automatically add it as a pitest dependency at runtime.
@nikomall34 has already created a PR in that direction: #168.
Obviously if POs prefer the coverage reporter bundled as a jar with either the jetbrains or gradle plugin that is still doable but the IP had the very valid concern that direct bundling of a .jar with either of the plugins will make versioning a nightmare, whereas having a published version merely requires changing the version string.
