### ISSUE TITLE
Create checklist for demo day presentation and finish slides

### ISSUE THREAD

**Issue by emuguy1** [amosproj/amos2023ws02-pitest-ide-plugin#198]
## User story

1. As a team member
2. I want / need a checklist/notes under each slide, what should be said
3. So that another team member can also present our projects

## Acceptance criteria

- Finish each slide from the draft
- For each slide, the talking points are noted 
- It is clear and understandable what should be said
- For the life demo there is a checklist with steps that should be shown
- the time limit for the presentation is respected
## Definition of done (DoD)

- All acceptance criteria are met.
- Work products are uploaded to the GitHub repository.
- A pull request is created for each related branch.
- The work products in the pull requests are reviewed.
- GitHub CI Workflow passes for the branches
- The corresponding branches are merged and closed.
- The bill of materials section of the planning documents is updated.
- Tests are written for the added features, if suitable

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by emuguy1** [comment]
Looking at the current status of the Presentation. Can you maybe try to put the important points from the recap also a bit more before, the recap adds new information, that seems odd to me.

**Comment by lfogarty98** [comment]
See updated version here: https://docs.google.com/presentation/d/1SaIfabefqpyIHblUmDb_miVd-CRxM89SciDsWsSFN-8/edit#slide=id.p

**Comment by emuguy1** [comment]
Did you also do a test run. Really test it out that it is 10 minutes and for the showcasing part, please write concrete classes, where there is some stuff to show.

**Comment by brianneoberson** [comment]
Yes, we tested it. The first part takes about 5-6 minutes and the demo about 3-4 minutes.
