### ISSUE TITLE
Files with multiple classes and clicking on one class in the project window results in both classes in the target classes

### ISSUE THREAD

**Issue by lheimbs** [amosproj/amos2023ws02-pitest-ide-plugin#206]
**Describe the bug**
Having multiple classes in one File, Intellij shows both the classes in the project window as child nodes of the file name:
![image](https://github.com/amosproj/amos2023ws02-pitest-ide-plugin/assets/37455726/44c87852-ef68-4e6a-99dd-b9a5794a4bbd)

The file `Palindrome.java` contains both the classes `MyEmptyClass` and `Palindrome`.
Running a pitest from the context menu for either class results in both classes always in the target classes.

**To Reproduce**

1. Have a file with multiple classes
2. Click on 'Run PIT Mutationmate' from the context menu for one of the classes
3. Observe both classes in the override section

**Expected behavior**
Only the clicked on class is included.

**Desktop (please complete the following information):**

- OS: Linux
- IntelliJ IDEA 2023.3.2 (Community Edition)
- Build #IC-233.13135.103, built on December 22, 2023

## Acceptance criteria
- Fix described bug

## Definition of done (DoD)

- All acceptance criteria are met.
- Work products are uploaded to the GitHub repository.
- A pull request is created for each related branch.
- The work products in the pull requests are reviewed.
- GitHub CI Workflow passes for the branches
- The corresponding branches are merged and closed.
- The bill of materials section of the planning documents is updated.
- Tests are written for the added features, if suitable

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by Johnson1s** [comment]
> **Describe the bug** Having multiple classes in one File, Intellij shows both the classes in the project window as child nodes of the file name: ![image](https://private-user-images.githubusercontent.com/37455726/299308562-44c87852-ef68-4e6a-99dd-b9a5794a4bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MTg1MzMsIm5iZiI6MTcwNzcxODIzMywicGF0aCI6Ii8zNzQ1NTcyNi8yOTkzMDg1NjItNDRjODc4NTItZWY2OC00ZTZhLTk5ZGQtYjlhNTc5NGE0YmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDA2MTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0M2M2OGI2Njk3OTRhODg4NjNmMTg5ZGQ1ZDU1MTQ4MTRkYmUxNTc1OWU4ZmJhY2E4MDNiY2FjOGI0NzhhMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BAzeK2urypsseyJgzAHFNVOr725mhmEULLY-030KSVA)
> 
> The file `Palindrome.java` contains both the classes `MyEmptyClass` and `Palindrome`. Running a pitest from the context menu for either class results in both classes always in the target classes.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Have a file with multiple classes
> 2. Click on 'Run PIT Mutationmate' from the context menu for one of the classes
> 3. Observe both classes in the override section
> 
> **Expected behavior** Only the clicked on class is included.
> 
> **Desktop (please complete the following information):**
> 
> * OS: Linux
> * IntelliJ IDEA 2023.3.2 (Community Edition)
> * Build #IC-233.13135.103, built on December 22, 2023
> 
> ## Acceptance criteria
> * Fix described bug
> 
> ## Definition of done (DoD)
> * All acceptance criteria are met.
> * Work products are uploaded to the GitHub repository.
> * A pull request is created for each related branch.
> * The work products in the pull requests are reviewed.
> * GitHub CI Workflow passes for the branches
> * The corresponding branches are merged and closed.
> * The bill of materials section of the planning documents is updated.
> * Tests are written for the added features, if suitable
> 
> ## DoD general criteria
> * Feature has been fully implemented
> * Feature has been merged into the mainline
> * All acceptance criteria were met
> * Product owner approved features
> * All tests are passing
> * Developers agreed to release
