### ISSUE TITLE
ClassNotFoundException was logged by Kotlin Plugin

### ISSUE THREAD

**Issue by nikomall34** [amosproj/amos2023ws02-pitest-ide-plugin#215]
**Describe the bug**
During the usage of our Plugin in the sandbox-intellij-idea the following exception was logged (I guess by the kotlin plugin):
```
Exception "java.lang.ClassNotFoundException: org/jetbrains/kotlin/idea/codeInsight/BasicKotlinReferenceTransferableData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=org.jetbrains.kotlin.idea.codeInsight.BasicKotlinReferenceTransferableData
```

**To Reproduce**
Run the runIDE task and sometime this exception occured.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 2023.3.3

**Comment by lheimbs** [comment]
I don't see what we can do about this since it concerns the kotlin plugin

**Comment by emuguy1** [comment]
Closing this as it is nothing we can doand that concerns us
