### ISSUE TITLE
If a file has multiple classes and you open the package brakedown the filename is used instead of the class name

### ISSUE THREAD

**Issue by emuguy1** [amosproj/amos2023ws02-pitest-ide-plugin#221]
**Describe the bug**
If a file has multiple classes and you open the package brakedown the filename is used instead of the class name

**To Reproduce**
Run a pitest of a file with multiple classes in it. Open Package overview tab. There are multiple entries with the same filename corresponding to the different classes.

**Expected behavior**
The class name is displayed to the user 

## Acceptance criteria
- bug is fixed

## Definition of done (DoD)

- All acceptance criteria are met.
- Work products are uploaded to the GitHub repository.
- A pull request is created for each related branch.
- The work products in the pull requests are reviewed.
- GitHub CI Workflow passes for the branches
- The corresponding branches are merged and closed.
- The bill of materials section of the planning documents is updated.
- Tests are written for the added features, if suitable

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by nikomall34** [comment]
Update by the IP: We should do it exactly like pitest does it. So when there are multiple classes in a file the results will be aggregated so one file = one class. For this the coverage-reporter must be adjusted
