### ISSUE TITLE
The pluginchecker is executed too early

### ISSUE THREAD

**Issue by nikomall34** [amosproj/amos2023ws02-pitest-ide-plugin#224]
**Describe the bug**
When you open a new project or start the runIDE, especially after deleting all the .idea, .gradle, and build folders, the IDE requires a significant amount of time to start up. This is why the Launch activity is executed before the project is fully loaded. Consequently, the plugin checker is triggered prematurely, leading to the display of the error message in the tool window, even though both plugins are included in your build file.

**To Reproduce**
Open a project in Intellij or start the runIDE task

**Desktop (please complete the following information):**

- OS: Windows 11 and Linux
- Version IntelliJ IDEA 2023.3.2 (Community and Ultimate Edition)

**Comment by emuguy1** [comment]
Can we maybe add a manuall trigger for rechecking in the error tab as an easy fix @nikomall34

**Comment by nikomall34** [comment]
Yes we will consider it. @lheimbs and I had another idea which we wanted to try next sprint. If it is not working we will use a trigger.
