### ISSUE TITLE
Load PITest XML Files

### ISSUE THREAD

**Issue by Felix-012** [amosproj/amos2023ws02-pitest-ide-plugin#48]
## User Story

1. As a software developer,
2. I want / need to obtain an example XML report from PITest,
3. So that I can save it in our data representation class for further analysis and integration.

## Acceptance Criteria

- Successfully retrieve an example XML report generated by PITest.
- The XML report should include a variety of data points, such as mutation scores, detailed mutation results, and test coverage.
- The data from the XML report should be accurately mapped and saved into the designated data representation class.
- Ensure that the data representation class preserves the structure and integrity of the information from the PITest report.
- Implement error handling to manage potential issues during the XML report parsing and data saving process.
- The solution should be scalable to handle XML reports of varying sizes and complexities.

## Definition of done (DoD)

- Acceptance criteria are met.
- Upload the work products to the GitHub repository or incorporate them into the wiki.
- The bill of materials section of the planning documents is updated.
- A pull request is created for each related branch.
- The work products in the pull requests are reviewed.
- The corresponding branches are merged and closed - (Without closing the Issue!).
- All specified conventions are complied with.

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by lheimbs** [comment]
default path: `build/reports/pitest/mutations.xml`
