### ISSUE TITLE
Familiarize with Pitest

### ISSUE THREAD

**Issue by emuguy1** [amosproj/amos2023ws02-pitest-ide-plugin#5]
## **User Story**
1. As a software development team
2. We want to familiarize ourselves with the Pitest Tool
3. Create a guide for other developers so they can easily start using the tool
## **Acceptance Criteria**
* Install and familiarize with Pitest.
* Gather information to get the tool started and start an easy example.
* Write a guide for other developers.
* Upload the guide to the wiki.

## **Definition of done (DoD)**
* Acceptance criteria are met.
* Be able to demo the software in the Sprint review

## **DoD General Criteria**
* All design and documentation tasks are finalized.
* All criteria are satisfied.
* The team lead or product owner approves the guide and the planning document is updated if needed.

**Comment by lfogarty98** [comment]
Pitest with Gradle sample: https://github.com/e-solutions-GmbH/pitest-gradle-sample

**Comment by lfogarty98** [comment]
Pitest Gradle plug-in installation guide: https://gradle-pitest-plugin.solidsoft.info/

**Comment by Pfoerd** [comment]
Hi. As promised, here is another example for Pitest: As promised, here is another more recent example: https://github.com/Pfoerd/pitest-gradle-example
